apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xnassimulator
  name: xnassimulator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xnassimulator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xnassimulator
    spec:
      containers:
      - env:
        - name: FIX_FILE_STORE_PATH
          value: /usr/share/cnoms/xnassimulator
        - name: TARGET_COMP_IDS
          value: xnas-order-gateway-0,xnas-order-gateway-1,xnas-order-gateway-2
        image: {{ .Values.dockerRepo }}fixmarketsimulator{{ .Values.dockerTag }}
        imagePullPolicy: Always
        name: xnassimulator
        ports:
        - containerPort: 9876
          name: fix-server
          protocol: TCP
        - containerPort: 8500
          name: open-api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/cnoms
          name: fixsim-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: fixsim-storage

